version: '3.3'

services:
  database:
    image: mysql:5.6
    container_name: bd-trabalho-formulario-cidadao
    ports:
      - "3306:3306"
    volumes:
      - ./dados:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=vamospassar
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: phpmyadmin-trabalho-formulario-cidadao
    ports:
      - "8000:80"
    links:
      - database
    environment:
      - PMA_ARBITRARY=1
